development:
  adapter: postgresql
  encoding: unicode
  database: rumble_development
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password:
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: rumble_test
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password:
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  database: rumble_production
  pool: 5
  host: localhost
  username: rumble
  password: horaextra13
